import { Component, OnInit, Input, HostListener, OnChanges } from '@angular/core';
import * as d3 from 'd3'; //NOTE: maybe import individual components??
import d3Tip from 'd3-tip';
import { BehaviorSubject } from 'rxjs';



@Component({
  selector: 'mev-bubble-plot',
  templateUrl: './bubble-plot.component.html',
  styleUrls: ['./bubble-plot.component.scss']
})

export class TopGoBubblePlotComponent implements OnChanges {
  private _data = new BehaviorSubject([]);

  @Input() data



  dataInput = [];
  // dataInput = [
  //   {
  //     "go_id": "GO:0008146",
  //     "term": "sulfotransferase activity",
  //     "annotated": 47,
  //     "significant": 45,
  //     "expected": 36.37,
  //     "fisher_rank": 13,
  //     "classic_pval": 0.0006,
  //     "elim_pval": 0.0006,
  //     "genelist": [
  //       "SULT1E1",
  //       "SULT1A2",
  //       "SULT1A1",
  //       "SULT1A3",
  //       "SULT1C2",
  //       "SULT2B1",
  //       "SULT2A1",
  //       "TPST2",
  //       "TPST1",
  //       "CHST1",
  //       "HS6ST1",
  //       "CHST2",
  //       "CHST3",
  //       "CHST10",
  //       "GAL3ST1",
  //       "HS2ST1",
  //       "HS3ST3A1",
  //       "HS3ST2",
  //       "HS3ST1",
  //       "UST",
  //       "CHST4",
  //       "WSCD1",
  //       "CHST5",
  //       "SULT4A1",
  //       "SULT1C4",
  //       "SULT1B1",
  //       "CHST11",
  //       "CHST12",
  //       "GAL3ST2",
  //       "CHST8",
  //       "GAL3ST4",
  //       "CHST9",
  //       "GAL3ST3",
  //       "DSEL",
  //       "CHST14",
  //       "CHST13",
  //       "SULT6B1",
  //       "SULT1C3",
  //       "SULT1A4"
  //     ]
  //   },
  //   {
  //     "go_id": "GO:0005249",
  //     "term": "voltage-gated potassium channel activity",
  //     "annotated": 79,
  //     "significant": 72,
  //     "expected": 61.13,
  //     "fisher_rank": 17,
  //     "classic_pval": 0.0012,
  //     "elim_pval": 0.0012,
  //     "genelist": [
  //       "HCN2",
  //       "KCNA1",
  //       "KCNA2",
  //       "KCNA3",
  //       "KCNA4",
  //       "KCNA5",
  //       "KCNA6",
  //       "KCNA7",
  //       "KCNA10",
  //       "KCNB1",
  //       "KCNC1",
  //       "KCNC2",
  //       "KCNC3",
  //       "KCNC4",
  //       "KCND1",
  //       "KCND2",
  //       "KCND3",
  //       "KCNE1",
  //       "KCNF1",
  //       "KCNG1",
  //       "KCNH1",
  //       "KCNH2",
  //       "KCNJ11",
  //       "KCNMA1",
  //       "KCNQ1",
  //       "KCNQ2",
  //       "KCNQ3",
  //       "KCNS1",
  //       "KCNS2",
  //       "KCNS3",
  //       "PKD2",
  //       "SNAP25",
  //       "KCNAB1",
  //       "KCNAB2",
  //       "KCNQ4",
  //       "KCNAB3",
  //       "KCNB2",
  //       "HCN4",
  //       "KCNH4",
  //       "KCNH3",
  //       "KCNE5",
  //       "KCNG2",
  //       "KCNV1",
  //       "KCNH5",
  //       "KCNK9",
  //       "KCNQ5",
  //       "HCN3",
  //       "KCNH6",
  //       "KCNH7",
  //       "KCNG4",
  //       "LRRC38",
  //       "KCNH8",
  //       "KCNV2",
  //       "KCNG3",
  //       "LRRC55",
  //       "HCN1",
  //       "LRRC26",
  //       "LRRC52"
  //     ]
  //   },
  //   {
  //     "go_id": "GO:0046943",
  //     "term": "carboxylic acid transmembrane transporte...",
  //     "annotated": 143,
  //     "significant": 125,
  //     "expected": 110.65,
  //     "fisher_rank": 25,
  //     "classic_pval": 0.0016,
  //     "elim_pval": 0.0016,
  //     "genelist": [
  //       "AQP9",
  //       "ABCC1",
  //       "ABCB1",
  //       "SLC16A1"
  //     ]
  //   },
  //   {
  //     "go_id": "GO:0005198",
  //     "term": "structural molecule activity",
  //     "annotated": 614,
  //     "significant": 515,
  //     "expected": 475.1,
  //     "fisher_rank": 3,
  //     "classic_pval": 0,
  //     "elim_pval": 0.0017,
  //     "genelist": [
  //       "JAG1",
  //       "ANK1",
  //       "APOE",
  //       "ASPH",
  //       "BGLAP",
  //       "DST",
  //       "SEPTIN7",
  //       "CLTA",
  //       "CLTB",
  //       "CLTC",
  //       "COL4A3",
  //       "COPA",
  //       "COPB1",
  //       "CLDN4",
  //       "CLDN3",
  //       "CLDN7",
  //       "CRYAA",
  //       "CRYAB",
  //       "CRYBB2",
  //       "CTNNA1",
  //       "CYLC1",
  //       "DSP",
  //       "EPB41L1",
  //       "EPB41L2",
  //       "STX2",
  //       "EVPL",
  //       "FGA",
  //       "FGB",
  //       "FGG",
  //       "FLG",
  //       "GNL1",
  //       "HMGCL",
  //       "HMOX1",
  //       "JUP",
  //       "KRT12",
  //       "KRT13",
  //       "KRT17",
  //       "KRT18",
  //       "KRT32",
  //       "KRT33A",
  //       "KRT33B",
  //       "KRT34",
  //       "KRT35",
  //       "KRT85",
  //       "LAD1",
  //       "LAMA2",
  //       "LAMA3",
  //       "LAMB1",
  //       "LAMB2",
  //       "LAMB3",
  //       "LLGL1",
  //       "LMNB1",
  //       "MAP1A",
  //       "MAP1B",
  //       "MAP2",
  //       "MAP4",
  //       "MPZ",
  //       "NPHP1",
  //       "NUMA1",
  //       "ODF2",
  //       "CLDN11",
  //       "PGM5",
  //       "PLEC",
  //       "PLP1",
  //       "PNN",
  //       "SEPTIN5",
  //       "SEPTIN4",
  //       "PPL",
  //       "PRPH",
  //       "PSMD11",
  //       "PSMD13",
  //       "SEC13",
  //       "SNTA1",
  //       "SNTB1",
  //       "SNTB2",
  //       "SPAG4",
  //       "SPRR1A",
  //       "SPRR1B",
  //       "SPRR2E",
  //       "SPRR3",
  //       "TGM3",
  //       "CLDN5",
  //       "UPK1B",
  //       "VCL",
  //       "TUBA1A",
  //       "CLTCL1",
  //       "EIF3A",
  //       "KRT38",
  //       "KRT37",
  //       "MPZL1",
  //       "MAP7",
  //       "CLDN10",
  //       "CLDN8",
  //       "CLDN6",
  //       "CLDN2",
  //       "CLDN1",
  //       "CLDN9",
  //       "KRT75",
  //       "COPB2",
  //       "ROCK2",
  //       "CROCC",
  //       "MATR3",
  //       "LAMC3",
  //       "TUBA1B",
  //       "TUBGCP3",
  //       "OLFM4",
  //       "CLDN16",
  //       "BVES",
  //       "DCTN3",
  //       "COPE",
  //       "COPG1",
  //       "SEC31A",
  //       "MACF1",
  //       "MAPK8IP2",
  //       "CLDN14",
  //       "PANX1",
  //       "CLDN15",
  //       "SEC31B",
  //       "KRT23",
  //       "KLHL3",
  //       "CLDN17",
  //       "COPG2",
  //       "TUBG2",
  //       "CLDN20",
  //       "CLDN18",
  //       "CLDN22",
  //       "SNTG1",
  //       "SNTG2",
  //       "PANX2",
  //       "ERVK-5",
  //       "ERVK-6",
  //       "ISCA1",
  //       "SEH1L",
  //       "EPPK1",
  //       "TLN2",
  //       "KRTAP3-1",
  //       "KRTAP3-2",
  //       "VPS25",
  //       "TUBA1C",
  //       "KRTAP3-3",
  //       "PANX3",
  //       "ISCA2",
  //       "KRT222",
  //       "KRT40",
  //       "CLDN23",
  //       "KRT25",
  //       "CLDN19",
  //       "KRT28",
  //       "KRT24",
  //       "TUBB",
  //       "NPHP4",
  //       "OTOG",
  //       "KRT27",
  //       "KRT26",
  //       "FLG2",
  //       "KRT39",
  //       "ERVK-7",
  //       "KRTAP24-1",
  //       "CLDN25",
  //       "EVPLL",
  //       "CLDN24",
  //       "CLDN34",
  //       "ERVK13-1",
  //       "ERVK-21",
  //       "ERVK-24"
  //     ]
  //   },
  //   {
  //     "go_id": "GO:0005102",
  //     "term": "signaling receptor binding",
  //     "annotated": 1381,
  //     "significant": 1112,
  //     "expected": 1068.6,
  //     "fisher_rank": 26,
  //     "classic_pval": 0.0017,
  //     "elim_pval": 0.0017,
  //     "genelist": [
  //       "A2M",
  //       "ABCA1",
  //       "ADAM10",
  //       "ADCYAP1",
  //       "ADM",
  //       "AGRP",
  //       "ALCAM",
  //       "AMH",
  //       "ANG",
  //       "ANGPT1",
  //       "ANGPT2",
  //       "ANXA1",
  //       "APOF",
  //       "APOA1",
  //       "APOA2",
  //       "APOE",
  //       "APP",
  //       "FASLG",
  //       "AR",
  //       "ARRB2",
  //       "ASIP",
  //       "AVP",
  //       "BLK",
  //       "BMP2",
  //       "BMP3",
  //       "BOK",
  //       "BTN1A1",
  //       "C3",
  //       "C5",
  //       "CAV1",
  //       "CD2",
  //       "CD22",
  //       "TNFSF8",
  //       "CD58",
  //       "CD70",
  //       "CD72",
  //       "CDH5",
  //       "CLU",
  //       "CNTFR",
  //       "CRH",
  //       "CSNK2B",
  //       "CTNND1",
  //       "DIAPH1",
  //       "DIAPH2",
  //       "DPP4",
  //       "DVL3",
  //       "EDA",
  //       "EDN3",
  //       "EFNA1",
  //       "ENSA",
  //       "DMTN",
  //       "EPHB2",
  //       "F2",
  //       "F2R",
  //       "F2RL1",
  //       "F7",
  //       "PTK2B",
  //       "FCN1",
  //       "FCN2",
  //       "FER",
  //       "FES",
  //       "FGA",
  //       "FGB",
  //       "FGG",
  //       "FGL1",
  //       "FGR",
  //       "FKBP1B",
  //       "FLT3LG",
  //       "FN1",
  //       "FRK",
  //       "FYB1",
  //       "FYN",
  //       "GAS6",
  //       "GBA",
  //       "GCG",
  //       "MSTN",
  //       "GDNF",
  //       "GFRA1",
  //       "GFRA3",
  //       "GLA",
  //       "GLG1",
  //       "MCHR1",
  //       "CXCL1",
  //       "GRP",
  //       "GSK3A",
  //       "GSTM2",
  //       "GUSB",
  //       "HCK",
  //       "HFE",
  //       "NRG1",
  //       "HLA-A",
  //       "HLA-B",
  //       "HLA-E",
  //       "HLA-F",
  //       "HLA-G",
  //       "HLA-H",
  //       "HNF4A",
  //       "HRG",
  //       "HSPA1A",
  //       "HSPA1B",
  //       "IAPP",
  //       "ICAM3",
  //       "IDUA",
  //       "IGFBP1",
  //       "IGFBP2",
  //       "IGFBP4",
  //       "IGFBP6",
  //       "INHA",
  //       "CXCL10",
  //       "INSL3",
  //       "INSL4",
  //       "ITGA1",
  //       "JAK2",
  //       "KCNA5",
  //       "KNG1",
  //       "LAMA2",
  //       "LAMA4",
  //       "LAMC2",
  //       "LBP",
  //       "LCK",
  //       "LCN1",
  //       "LHB",
  //       "LIF",
  //       "LPL",
  //       "LRP6",
  //       "LRPAP1",
  //       "LTA",
  //       "LTB",
  //       "LYN",
  //       "MAG",
  //       "MBL2",
  //       "MFAP4",
  //       "MOG",
  //       "MSN",
  //       "MYO1C",
  //       "NCK1",
  //       "NPY",
  //       "NPPA",
  //       "NPPB",
  //       "NPPC",
  //       "NRTN",
  //       "NTF3",
  //       "NTN3",
  //       "P2RX4",
  //       "P2RX7",
  //       "SERPINE1",
  //       "PDGFRB",
  //       "PEX14",
  //       "SERPINE2",
  //       "PKD2",
  //       "PLA2G1B",
  //       "PLAT",
  //       "PLAUR",
  //       "PLG",
  //       "POMC",
  //       "PTPA",
  //       "PSPN",
  //       "PRTN3",
  //       "PTK2",
  //       "PTK6",
  //       "PTPRC",
  //       "PTPRD",
  //       "RARA",
  //       "RARRES2",
  //       "RASA1",
  //       "REN",
  //       "SCP2",
  //       "SCT",
  //       "CCL2",
  //       "CCL13",
  //       "CCL15",
  //       "CCL17",
  //       "CX3CL1",
  //       "CXCL12",
  //       "SELPLG",
  //       "SIX3",
  //       "SLA",
  //       "SLC6A3",
  //       "SMARCD1",
  //       "SMARCD3",
  //       "SRC",
  //       "SRI",
  //       "SRMS",
  //       "ITPRID2",
  //       "SSTR3",
  //       "SYK",
  //       "TAC3",
  //       "TDGF1",
  //       "TDGF1P3",
  //       "TGFB2",
  //       "THPO",
  //       "TLR4",
  //       "TNR",
  //       "TRPC1",
  //       "TNFSF4",
  //       "TYROBP",
  //       "UFD1",
  //       "WNT7A",
  //       "YES1",
  //       "ZAP70",
  //       "BAG6",
  //       "FZD1",
  //       "TMEFF1",
  //       "NPFF",
  //       "TNK1",
  //       "TNFSF14",
  //       "TNFSF10",
  //       "TNFSF9",
  //       "RIPK2",
  //       "TRIM24",
  //       "APLN",
  //       "TNFSF18",
  //       "HAP1",
  //       "ARTN",
  //       "MAP7",
  //       "ANGPTL1",
  //       "LGI1",
  //       "SLC9A3R2",
  //       "SLC9A3R1",
  //       "ADIPOQ",
  //       "PICK1",
  //       "NRG2",
  //       "SNX17",
  //       "MTSS1",
  //       "TESPA1",
  //       "LRIG2",
  //       "TNFSF15",
  //       "AKAP9",
  //       "PLXNC1",
  //       "TNK2",
  //       "ANGPTL7",
  //       "TLR6",
  //       "TRDN",
  //       "BTN3A3",
  //       "BTN2A2",
  //       "RACK1",
  //       "SEMA4D",
  //       "PDPN",
  //       "CNPY3",
  //       "NRG3",
  //       "GIPC1",
  //       "TRAF3IP2",
  //       "ARPP19",
  //       "HCST",
  //       "NMU",
  //       "FGL2",
  //       "C1QL1",
  //       "UTS2",
  //       "BTNL3",
  //       "TMED1",
  //       "BTN3A2",
  //       "BTN3A1",
  //       "BTN2A1",
  //       "CD160",
  //       "IL1RAPL1",
  //       "GLMN",
  //       "HHLA2",
  //       "STRAP",
  //       "WIF1",
  //       "NXPH4",
  //       "NXPH3",
  //       "NXPH2",
  //       "PARK7",
  //       "TRAK1",
  //       "ICOSLG",
  //       "ZDHHC17",
  //       "ANGPTL2",
  //       "CLCF1",
  //       "LILRA4",
  //       "CADM1",
  //       "APOL2",
  //       "EML2",
  //       "PANX1",
  //       "ABCA12",
  //       "FGF20",
  //       "BEX3",
  //       "NSG1",
  //       "SLC39A1",
  //       "SRPX2",
  //       "RND1",
  //       "ANGPTL3",
  //       "PCSK1N",
  //       "HILPDA",
  //       "NXPH1",
  //       "STOML2",
  //       "ANGPTL4",
  //       "EGFL7",
  //       "ANGPT4",
  //       "RAB8B",
  //       "CYTL1",
  //       "BTN2A3P",
  //       "LEPROT",
  //       "BANK1",
  //       "WIPI1",
  //       "ANO1",
  //       "STYK1",
  //       "SCYL2",
  //       "PECR",
  //       "BEX1",
  //       "ERBIN",
  //       "CFC1",
  //       "BTNL2",
  //       "CRTAM",
  //       "SEMA3G",
  //       "CHRNA10",
  //       "NPVF",
  //       "CAPRIN2",
  //       "TRAK2",
  //       "DDX54",
  //       "VTCN1",
  //       "BTNL8",
  //       "CD276",
  //       "EGFL8",
  //       "WNT5B",
  //       "ANKRD13C",
  //       "AMN",
  //       "ANGPTL6",
  //       "BEX2",
  //       "IL17RC",
  //       "RSPO3",
  //       "FIBCD1",
  //       "WNT3A",
  //       "LRRC4B",
  //       "STX1B",
  //       "ERMAP",
  //       "PIK3AP1",
  //       "NTN5",
  //       "IGFL2",
  //       "HJV",
  //       "BTNL9",
  //       "TIGIT",
  //       "VWDE",
  //       "ITPRID1",
  //       "CNPY4",
  //       "IL27",
  //       "IFNL2",
  //       "IFNL3",
  //       "IFNL1",
  //       "LAMA1",
  //       "IZUMO1",
  //       "RSPO1",
  //       "RSPO2",
  //       "BEX5",
  //       "OSTN",
  //       "IGFL1",
  //       "IGFL3",
  //       "IZUMO1R",
  //       "IGFL4",
  //       "GUSBP3",
  //       "CFC1B",
  //       "BTNL10",
  //       "IFNL4"
  //     ]
  //   },
  //   {
  //     "go_id": "GO:0005201",
  //     "term": "extracellular matrix structural constitu...",
  //     "annotated": 158,
  //     "significant": 137,
  //     "expected": 122.26,
  //     "fisher_rank": 28,
  //     "classic_pval": 0.0021,
  //     "elim_pval": 0.0021,
  //     "genelist": [
  //       "AEBP1",
  //       "ACAN",
  //       "BGN",
  //       "CD4",
  //       "CHI3L1",
  //       "COL1A1",
  //       "COL1A2",
  //       "COL2A1",
  //       "COL3A1",
  //       "COL4A1",
  //       "COL4A2",
  //       "COL4A3",
  //       "COL4A4",
  //       "COL4A5",
  //       "COL4A6",
  //       "COL5A1",
  //       "COL5A2",
  //       "COL8A1",
  //       "COL8A2",
  //       "COL9A1",
  //       "COL9A2",
  //       "COL9A3",
  //       "COL10A1",
  //       "COL11A1",
  //       "COL11A2",
  //       "COL13A1",
  //       "COL15A1",
  //       "COL16A1",
  //       "COL17A1",
  //       "COL19A1",
  //       "COMP",
  //       "DPT",
  //       "DSPP",
  //       "ECM1",
  //       "ELN",
  //       "FBLN1",
  //       "FBLN2",
  //       "FBN1",
  //       "FBN2",
  //       "EFEMP1",
  //       "FGA",
  //       "FGB",
  //       "FGG",
  //       "FN1",
  //       "GP2",
  //       "TNC",
  //       "IGFBP7",
  //       "CCN1",
  //       "IMPG1",
  //       "ANOS1",
  //       "LAMA2",
  //       "LAMA3",
  //       "LAMA4",
  //       "LAMA5",
  //       "LAMB1",
  //       "LAMB2",
  //       "LAMB3",
  //       "LAMC1",
  //       "LAMC2",
  //       "LTBP1",
  //       "LTBP2",
  //       "LUM",
  //       "MATN1",
  //       "MATN2",
  //       "MATN3",
  //       "MFAP2",
  //       "MFAP4",
  //       "MFGE8",
  //       "MGP",
  //       "MUC3A",
  //       "MUC5AC",
  //       "MUC6",
  //       "NID1",
  //       "PCOLCE",
  //       "PRELP",
  //       "SPARC",
  //       "TECTB",
  //       "TECTA",
  //       "TGFBI",
  //       "THBS1",
  //       "THBS2",
  //       "THBS3",
  //       "TNXB",
  //       "UMOD",
  //       "COL14A1",
  //       "VTN",
  //       "VWF",
  //       "ZP3",
  //       "PXDN",
  //       "TFPI2",
  //       "MFAP5",
  //       "COLQ",
  //       "SRPX",
  //       "LTBP4",
  //       "CILP",
  //       "ADIPOQ",
  //       "EDIL3",
  //       "SPON1",
  //       "POSTN",
  //       "FGL2",
  //       "EMILIN1",
  //       "NID2",
  //       "LAMB4",
  //       "MMRN1",
  //       "MXRA5",
  //       "ABI3BP",
  //       "OPTC",
  //       "SRPX2",
  //       "EFEMP2",
  //       "COL5A3",
  //       "IMPG2",
  //       "MEPE",
  //       "TINAGL1",
  //       "VWA1",
  //       "CRELD1",
  //       "MMRN2",
  //       "THSD4",
  //       "FRAS1",
  //       "COL18A1",
  //       "HMCN1",
  //       "FBN3",
  //       "COL27A1",
  //       "UMODL1",
  //       "COL23A1",
  //       "CTHRC1",
  //       "OTOL1",
  //       "ZPLD1",
  //       "SBSPON",
  //       "COL22A1",
  //       "OIT3",
  //       "COL24A1",
  //       "NPNT",
  //       "HMCN2",
  //       "LAMA1",
  //       "COL28A1",
  //       "AGRN",
  //       "MARCOL"
  //     ]
  //   },
  //   {
  //     "go_id": "GO:0004867",
  //     "term": "serine-type endopeptidase inhibitor acti...",
  //     "annotated": 81,
  //     "significant": 73,
  //     "expected": 62.68,
  //     "fisher_rank": 30,
  //     "classic_pval": 0.0024,
  //     "elim_pval": 0.0024,
  //     "genelist": [
  //       "A2M",
  //       "SERPINA3",
  //       "AGT",
  //       "AMBP",
  //       "ANXA2",
  //       "APLP2",
  //       "APP",
  //       "SERPINC1",
  //       "SERPING1",
  //       "SERPINA6",
  //       "SERPINH1",
  //       "COL6A3",
  //       "COL7A1",
  //       "SERPINB1",
  //       "SERPIND1",
  //       "HRG",
  //       "ITIH1",
  //       "ITIH2",
  //       "ITIH3",
  //       "ITIH4",
  //       "ANOS1",
  //       "PEBP1",
  //       "FURIN",
  //       "SERPINE1",
  //       "SERPINB2",
  //       "SERPINA5",
  //       "SERPINF1",
  //       "SERPINA1",
  //       "PI3",
  //       "SERPINA4",
  //       "SERPINB5",
  //       "SERPINB6",
  //       "SERPINE2",
  //       "SERPINB8",
  //       "SERPINB9",
  //       "SERPINB10",
  //       "SERPINI1",
  //       "SERPINB13",
  //       "SERPINI2",
  //       "SERPINF2",
  //       "PZP",
  //       "SERPINB3",
  //       "SERPINB4",
  //       "SLPI",
  //       "SPINK1",
  //       "SPINK2",
  //       "SPINT1",
  //       "SPOCK1",
  //       "SERPINA7",
  //       "TFPI",
  //       "TFPI2",
  //       "RECK",
  //       "SERPINB7",
  //       "WFDC2",
  //       "SPINT2",
  //       "SPINT3",
  //       "SPINK5",
  //       "CPAMD8",
  //       "SPINK4",
  //       "PCSK1N",
  //       "SERPINA10",
  //       "CRIM1",
  //       "EPPIN",
  //       "WFDC1",
  //       "ITIH5",
  //       "SPINK7",
  //       "SERPINB12",
  //       "SERPINB11",
  //       "PAPLN",
  //       "WFDC8",
  //       "WFIKKN1",
  //       "WFIKKN2",
  //       "WFDC12",
  //       "CD109",
  //       "WFDC3",
  //       "WFDC10A",
  //       "OVOS2",
  //       "A2ML1",
  //       "SERPINA12",
  //       "WFDC5",
  //       "SPINK13",
  //       "WFDC13",
  //       "SERPINA11",
  //       "WFDC11",
  //       "WFDC9",
  //       "WFDC10B",
  //       "HMSD",
  //       "SERPINA9",
  //       "COL28A1",
  //       "ITIH6",
  //       "SERPINA2",
  //       "SPINT4",
  //       "SPINK6",
  //       "LOC408186",
  //       "SPINK14",
  //       "SPINK9",
  //       "SPINK8",
  //       "SERPINE3"
  //     ]
  //   },
  //   {
  //     "go_id": "GO:0003682",
  //     "term": "chromatin binding",
  //     "annotated": 502,
  //     "significant": 414,
  //     "expected": 388.44,
  //     "fisher_rank": 31,
  //     "classic_pval": 0.0027,
  //     "elim_pval": 0.0027,
  //     "genelist": [
  //       "ACTL6A",
  //       "APBB1",
  //       "AIRE",
  //       "AR",
  //       "ASCL1",
  //       "RERE",
  //       "ATRX",
  //       "BCL6",
  //       "POLR3D",
  //       "CCNT1",
  //       "CCNT2",
  //       "CDK9",
  //       "CEBPA",
  //       "CEBPB",
  //       "CENPA",
  //       "CENPB",
  //       "CENPF",
  //       "RCC1",
  //       "CKS2",
  //       "CORT",
  //       "ATF2",
  //       "CREBBP",
  //       "CSNK2B",
  //       "NKX2-5",
  //       "CTBP2",
  //       "CTNNB1",
  //       "DDX1",
  //       "DDX11",
  //       "DLX1",
  //       "DLX2",
  //       "DLX3",
  //       "DMRT1",
  //       "DNMT3A",
  //       "DNMT3B",
  //       "ARID3A",
  //       "PHC1",
  //       "PHC2",
  //       "EGFR",
  //       "EGR2",
  //       "ELK1",
  //       "ELK4",
  //       "EP300",
  //       "ERCC6",
  //       "ERG",
  //       "ESR1",
  //       "EZH1",
  //       "EZH2",
  //       "FABP1",
  //       "FOXO1",
  //       "FLI1",
  //       "FMR1",
  //       "FOS",
  //       "FOSL2",
  //       "NR5A2",
  //       "NR5A1",
  //       "FUS",
  //       "GABPA",
  //       "GATA2",
  //       "GATA6",
  //       "KAT2A",
  //       "GLI1",
  //       "GLI3",
  //       "GPER1",
  //       "MSH6",
  //       "GTF2H1",
  //       "HCFC1",
  //       "HDAC2",
  //       "HELLS",
  //       "HMGN1",
  //       "HMGN2",
  //       "HMGA1",
  //       "FOXA1",
  //       "HNF4A",
  //       "ONECUT1",
  //       "HNRNPD",
  //       "HNRNPU",
  //       "HOXC13",
  //       "HOXD10",
  //       "HOXD13",
  //       "RBPJ",
  //       "ING2",
  //       "JARID2",
  //       "SMAD2",
  //       "SMAD4",
  //       "SMAD6",
  //       "MECP2",
  //       "MEF2A",
  //       "MEIS1",
  //       "MEN1",
  //       "MEOX1",
  //       "MITF",
  //       "MLH1",
  //       "MLLT3",
  //       "MNT",
  //       "MPO",
  //       "CITED1",
  //       "MSH2",
  //       "TRIM37",
  //       "MYOD1",
  //       "NAP1L1",
  //       "NAP1L2",
  //       "NAP1L3",
  //       "NAP1L4",
  //       "NEUROD1",
  //       "NEUROG1",
  //       "NFATC2",
  //       "NFIA",
  //       "NFKB1",
  //       "NKX6-1",
  //       "NONO",
  //       "NPM1",
  //       "ORC1",
  //       "PBX2",
  //       "PCNA",
  //       "PHF1",
  //       "PKNOX1",
  //       "POLA1",
  //       "POLD1",
  //       "POLE",
  //       "POLG",
  //       "POLR2B",
  //       "POU4F1",
  //       "PPARG",
  //       "MED1",
  //       "PRKAA1",
  //       "PRKAA2",
  //       "PRKCB",
  //       "PKN1",
  //       "RAD17",
  //       "RAD21",
  //       "RAD51",
  //       "RAG2",
  //       "RAN",
  //       "RARA",
  //       "RARG",
  //       "RELA",
  //       "UPF1",
  //       "REST",
  //       "RIT2",
  //       "RING1",
  //       "RNF2",
  //       "BRD2",
  //       "SAFB",
  //       "SCML1",
  //       "SET",
  //       "SFPQ",
  //       "SHMT2",
  //       "SIX1",
  //       "SKIL",
  //       "SMARCA2",
  //       "SMARCD1",
  //       "SMARCD3",
  //       "SMARCE1",
  //       "SOX9",
  //       "SOX15",
  //       "SP3",
  //       "SREBF1",
  //       "SSBP1",
  //       "STAT5B",
  //       "SUPT5H",
  //       "SUV39H1",
  //       "TADA2A",
  //       "TAF2",
  //       "TAL1",
  //       "TFAM",
  //       "TFAP2A",
  //       "TFAP2B",
  //       "TOP1",
  //       "TOP2A",
  //       "TOP2B",
  //       "TP53",
  //       "TPR",
  //       "TSPY1",
  //       "TSPYL1",
  //       "TTF1",
  //       "UBTF",
  //       "NSD2",
  //       "WRN",
  //       "YY1",
  //       "NELFE",
  //       "BRD3",
  //       "MLLT10",
  //       "CHAF1B",
  //       "SMC1A",
  //       "BAP1",
  //       "CDC45",
  //       "SOX14",
  //       "UXT",
  //       "CBX4",
  //       "BARX2",
  //       "TP63",
  //       "NCOA1",
  //       "URI1",
  //       "TRIM24",
  //       "HESX1",
  //       "HDAC3",
  //       "KAT2B",
  //       "LDB1",
  //       "MCM3AP",
  //       "RNF8",
  //       "MTA1",
  //       "SMC3",
  //       "EXO1",
  //       "HMGN3",
  //       "CDYL",
  //       "NCOR2",
  //       "PCLAF",
  //       "SETDB1",
  //       "NCAPD2",
  //       "MED12",
  //       "REC8",
  //       "HDAC5",
  //       "CHAF1A",
  //       "SMC4",
  //       "TRIM28",
  //       "STAG1",
  //       "NPM3",
  //       "NPM2",
  //       "CITED2",
  //       "SCML2",
  //       "YAP1",
  //       "SLC30A9",
  //       "HMGN4",
  //       "NCOA2",
  //       "SMC2",
  //       "POLR3G",
  //       "POLQ",
  //       "STAG3",
  //       "STAG2",
  //       "ZNF274",
  //       "CBX1",
  //       "NUDT21",
  //       "POLR3A",
  //       "WDHD1",
  //       "RBPJL",
  //       "ATF5",
  //       "MTF2",
  //       "MORC2",
  //       "BAHD1",
  //       "DHX30",
  //       "SIRT2",
  //       "SCMH1",
  //       "KDM1A",
  //       "NCOA6",
  //       "KDM4C",
  //       "CAMTA2",
  //       "PHF8",
  //       "RCOR1",
  //       "TSPYL4",
  //       "TASOR",
  //       "SIN3B",
  //       "NCAPD3",
  //       "SATB2",
  //       "NCAPH",
  //       "CBX5",
  //       "BRD4",
  //       "PATZ1",
  //       "NUP62",
  //       "NIPBL",
  //       "ASF1A",
  //       "POLR1A",
  //       "SIN3A",
  //       "HINFP",
  //       "L3MBTL1",
  //       "AUTS2",
  //       "ANKRD17",
  //       "PHF19",
  //       "NOC2L",
  //       "NUPR1",
  //       "VCX",
  //       "DNAJC2",
  //       "MLH3",
  //       "PELP1",
  //       "RBMX",
  //       "TOX3",
  //       "ATAD2",
  //       "UBE2T",
  //       "NCAPH2",
  //       "GMNN",
  //       "KMT5B",
  //       "MRNIP",
  //       "LEF1",
  //       "PLAC8",
  //       "PHF21A",
  //       "WAC",
  //       "ACTL6B",
  //       "SFMBT1",
  //       "SIRT7",
  //       "STAG3L1",
  //       "ATAD2B",
  //       "PAF1",
  //       "MPHOSPH8",
  //       "MBTD1",
  //       "BCAS3",
  //       "APTX",
  //       "FEZF2",
  //       "PRMT6",
  //       "PBRM1",
  //       "DPPA4",
  //       "ASXL2",
  //       "CHD7",
  //       "MBD5",
  //       "ASH1L",
  //       "RNF20",
  //       "SMARCAD1",
  //       "ENY2",
  //       "PRDM11",
  //       "MTA3",
  //       "CRAMP1",
  //       "BAHCC1",
  //       "TSHZ3",
  //       "EP400",
  //       "CALCOCO1",
  //       "CHD8",
  //       "FANCM",
  //       "SFMBT2",
  //       "NCOA5",
  //       "OVOL2",
  //       "TSPYL2",
  //       "NOC3L",
  //       "NSD1",
  //       "TSPY2",
  //       "EBF2",
  //       "NUCKS1",
  //       "STAG3L4",
  //       "HMGN5",
  //       "NKAP",
  //       "OBI1",
  //       "KDM8",
  //       "MCMBP",
  //       "PHC3",
  //       "ZC3H12A",
  //       "IFT74",
  //       "ZKSCAN3",
  //       "WDR82",
  //       "ASXL3",
  //       "SETD7",
  //       "TDRD3",
  //       "CDT1",
  //       "GRWD1",
  //       "L3MBTL2",
  //       "BRIP1",
  //       "ING5",
  //       "L3MBTL3",
  //       "MCM8",
  //       "TNRC18",
  //       "GLYR1",
  //       "CBX2",
  //       "KMT5C",
  //       "AJUBA",
  //       "TSPYL5",
  //       "SAMD1",
  //       "TICRR",
  //       "PYGO2",
  //       "CREB3L1",
  //       "L3MBTL4",
  //       "FAAP24",
  //       "TTC5",
  //       "TADA2B",
  //       "CDCA5",
  //       "MBD6",
  //       "PWWP2A",
  //       "CGAS",
  //       "KLHDC3",
  //       "ZNF354B",
  //       "FOXN4",
  //       "JDP2",
  //       "TSPY26P",
  //       "KLF14",
  //       "ARID3C",
  //       "ACTRT1",
  //       "SAMD11",
  //       "SAMD13",
  //       "PHF13",
  //       "DPPA2",
  //       "USP51",
  //       "RNF168",
  //       "ARX",
  //       "ZNF431",
  //       "ASXL1",
  //       "CRTC2",
  //       "PRIMPOL",
  //       "BEND6",
  //       "KDM1B",
  //       "LRWD1",
  //       "NKAPL",
  //       "MAPK15",
  //       "MCM9",
  //       "MEIOB",
  //       "PTF1A",
  //       "SCML4",
  //       "NAP1L5",
  //       "STPG4",
  //       "MSL1",
  //       "MSGN1",
  //       "SAMD7",
  //       "ZFP57",
  //       "ZNF445",
  //       "CENPS",
  //       "HES5",
  //       "TSPYL6",
  //       "STAG3L3",
  //       "STAG3L2",
  //       "RAD21L1",
  //       "SETSIP",
  //       "GMNC",
  //       "TSPY3",
  //       "TSPY4",
  //       "TSPY8",
  //       "EPOP",
  //       "TSPY10"
  //     ]
  //   },
  //   {
  //     "go_id": "GO:0008022",
  //     "term": "protein C-terminus binding",
  //     "annotated": 179,
  //     "significant": 153,
  //     "expected": 138.51,
  //     "fisher_rank": 37,
  //     "classic_pval": 0.0044,
  //     "elim_pval": 0.0044,
  //     "genelist": [
  //       "ABL1",
  //       "AP2A1",
  //       "ATF4",
  //       "ATP1B1",
  //       "DST",
  //       "BRCA2",
  //       "CACNA1B",
  //       "CAV3",
  //       "CDC20",
  //       "CDK7",
  //       "CENPF",
  //       "FOXN3",
  //       "CNGA3",
  //       "CSK",
  //       "CTBP1",
  //       "CCN2",
  //       "CTNNB1",
  //       "DAB2",
  //       "DAPK3",
  //       "DLG1",
  //       "DLG4",
  //       "ECM1",
  //       "EP300",
  //       "EPB41",
  //       "ERBB2",
  //       "ERCC1",
  //       "ERCC2",
  //       "ERCC3",
  //       "ERCC4",
  //       "ERCC6",
  //       "PTK2B",
  //       "FBLN1",
  //       "FN1",
  //       "XRCC6",
  //       "MCHR1",
  //       "HRAS",
  //       "HSPG2",
  //       "ID1",
  //       "JAK2",
  //       "KCNJ11",
  //       "KCNK3",
  //       "KPNA3",
  //       "LCK",
  //       "LIG4",
  //       "BCAM",
  //       "MAD2L1",
  //       "CIITA",
  //       "MKI67",
  //       "AFDN",
  //       "MRE11",
  //       "CITED1",
  //       "MSH2",
  //       "MYO1C",
  //       "NCF2",
  //       "NCL",
  //       "NEFL",
  //       "NPAT",
  //       "NUMA1",
  //       "OPRM1",
  //       "PCNA",
  //       "PEX1",
  //       "PEX6",
  //       "PEX12",
  //       "PFKM",
  //       "PHB",
  //       "POLR2A",
  //       "PPARG",
  //       "PPP1CC",
  //       "PPP2CA",
  //       "PPP2CB",
  //       "PRKAA1",
  //       "MAP2K1",
  //       "RAB3A",
  //       "RAD51",
  //       "ATXN1",
  //       "ATXN2",
  //       "SDC1",
  //       "SH3GL1",
  //       "SH3GL2",
  //       "SH3GL3",
  //       "SIAH1",
  //       "SIPA1",
  //       "SP1",
  //       "SRC",
  //       "SREBF2",
  //       "SYT1",
  //       "TAF13",
  //       "TBL1X",
  //       "TCF4",
  //       "DYNLT1",
  //       "TERF2",
  //       "TERT",
  //       "TESK1",
  //       "TNFAIP3",
  //       "TOP2A",
  //       "TOP2B",
  //       "EZR",
  //       "XRCC4",
  //       "XRCC5",
  //       "YWHAB",
  //       "ZBTB16",
  //       "USP7",
  //       "YEATS4",
  //       "COIL",
  //       "PIAS1",
  //       "DYNLL1",
  //       "MPDZ",
  //       "BANF1",
  //       "HESX1",
  //       "KSR1",
  //       "BCL10",
  //       "MAGI1",
  //       "SLC9A3R2",
  //       "PEX16",
  //       "PICK1",
  //       "VPS4B",
  //       "MDC1",
  //       "CEP135",
  //       "SNX17",
  //       "MED12",
  //       "SAE1",
  //       "OPTN",
  //       "PIAS3",
  //       "YAP1",
  //       "BAIAP2",
  //       "FBLN5",
  //       "CIB1",
  //       "RABAC1",
  //       "TRIM3",
  //       "PRDX3",
  //       "STIP1",
  //       "YWHAQ",
  //       "TOPBP1",
  //       "CORO1A",
  //       "CEP250",
  //       "SNF8",
  //       "PHB2",
  //       "MAPRE1",
  //       "MAPRE3",
  //       "HIC2",
  //       "PRRC2C",
  //       "SASH1",
  //       "SIRT1",
  //       "ITGB3BP",
  //       "GRIP1",
  //       "CD2AP",
  //       "EML2",
  //       "NIPBL",
  //       "CNRIP1",
  //       "PABPC1",
  //       "SDCBP2",
  //       "HSPB7",
  //       "AGO2",
  //       "VPS4A",
  //       "DBNL",
  //       "GPSM2",
  //       "TAX1BP3",
  //       "SHANK1",
  //       "VPS36",
  //       "TNNI3K",
  //       "IFT52",
  //       "SPTBN5",
  //       "HPCAL4",
  //       "VTA1",
  //       "PIAS4",
  //       "SNTG1",
  //       "RBFOX1",
  //       "FIGN",
  //       "PPP1R9A",
  //       "PEX26",
  //       "IFT46",
  //       "MIF4GD",
  //       "SCAF4",
  //       "CALCOCO1",
  //       "MID1IP1",
  //       "NEIL1",
  //       "PDZD3",
  //       "PPP1R9B",
  //       "PCGF1",
  //       "SHANK3",
  //       "EFHC1",
  //       "SCLT1",
  //       "CEP120",
  //       "VGLL2",
  //       "LAMA1"
  //     ]
  //   },
  //   {
  //     "go_id": "GO:0015079",
  //     "term": "potassium ion transmembrane transporter ...",
  //     "annotated": 143,
  //     "significant": 130,
  //     "expected": 110.65,
  //     "fisher_rank": 2,
  //     "classic_pval": 0,
  //     "elim_pval": 0.0049,
  //     "genelist": [
  //       "AQP1",
  //       "KCNA1",
  //       "SLC12A2"
  //     ]
  //   }
  // ]

  margin = {
    top: 50,
    right: 300,
    bottom: 50,
    left: 250
  }
  containerId = '#bubblePlot';
  outerHeight = 500;
  outerWidth = window.innerWidth
  xAxis: any;
  yAxis: any;
  xScale: any;
  yScale: any;
  radiusScale: any;
  xCat: any;
  yCat: any;
  gX: any;
  gY: any;
  xVariance: any;
  yVariance: any;
  precision = 2;
  maxAnnotated: any = 1300;
  minAnnotated: any = 0;
  maxRadius: any;
  minRadius: any;
  pointCat: any;
  colorMin: string = '#1DA1F2';
  colorMax: string = '#DF1F2D';
  sampleSetColors = [];

  colors = d3.scaleLinear<string>()
    .domain([this.minAnnotated, this.maxAnnotated])
    .range([this.colorMin, this.colorMax])

  ngOnChanges(): void {
    this.dataInput = this.data;
    this.updateColorRange()
    // this.createChart();
  }


  //might not need this??
  @HostListener('window:resize', ['$event'])
  onResize(event: any) {
    outerWidth = window.innerWidth;
    this.createChart()
  }

  private updateColorRange(): void {
    this.minAnnotated = d3.min(this.data, d => d.annotated);
    this.maxAnnotated = d3.max(this.data, d => d.annotated);
    this.maxRadius = d3.max(this.data, d => (d.significant / d.annotated));
    this.minRadius = d3.min(this.data, d => (d.significant / d.annotated));
    this.createChart()
  }

  private createChart(): void {
    const outerWidth = this.outerWidth;
    const outerHeight = this.outerHeight;
    const width = outerWidth - this.margin.left - this.margin.right;
    const height = outerHeight - this.margin.top - this.margin.bottom;
    const data = this.dataInput;

    d3.select(this.containerId)
      .selectAll('text')
      .remove();

    this.xScale = d3
      .scaleLinear()
      .domain([Math.log(this.minAnnotated), Math.log(this.maxAnnotated)])
      .rangeRound([0, width]) //vs rangeRound()
      .nice();

    this.yScale = d3
      .scaleBand()
      .domain(data.map(d => d.term))
      .rangeRound([0, height]);

    this.radiusScale = d3
      .scaleSqrt()
      .domain([this.minRadius, this.maxRadius])
      .range([3, height / (this.dataInput.length + 15)]);

    this.xAxis = d3.axisBottom(this.xScale).tickSize(-height);
    this.yAxis = d3.axisLeft(this.yScale).tickSize(-width);

    const group = d3
      .select(this.containerId)
      .append("text")
      .attr("x", (width / 2))
      .attr("y", 0 - (this.margin.top / 2))
      .attr("text-anchor", "middle")
      .classed('chart-title', true)
      .style("font-size", "16px")
      .text("TopGo Bubble Plot")
      .append('svg')
      .attr('width', outerWidth)
      .attr('height', outerHeight)
      .append('g')
      .attr(
        'transform',
        'translate(' + this.margin.left + ',' + this.margin.top + ')'
      )
      .style('fill', 'none')

    group
      .append('rect')
      .attr('width', width)
      .attr('height', height)

    this.gX = group
      .append('g')
      .classed('x axis', true)
      .attr('transform', 'translate(0,' + height + ')')
      .call(this.xAxis);

    this.gX
      .append('text')
      .classed('label', true)
      .attr('x', width / 2)
      .attr('y', this.margin.bottom - 10)
      .style('text-anchor', 'end')
      .text("-Log(P Value)");

    this.gY = group
      .append('g')
      .classed('y axis', true)
      .call(this.yAxis);

    this.gY
      .append('text')
      .classed('label', true)
      .attr('transform', 'rotate(-90)')
      .attr('y', -this.margin.left + 10)
      .attr('x', -height / 2)
      .attr('dy', '.71em')
      .style('text-anchor', 'middle')
      .text("GO Terms");

    const tip = d3Tip()
      .attr('class', 'd3-tip')
      .offset([-10, 0])
      .html((event, d) => {
        return "<strong>GO ID</strong>: <span>" + d.go_id + "</span> <br>" +
          "<strong>Term</strong>: <span>" + d.term + "</span><br>" +
          "<strong>GO ID</strong>: <span>" + d.go_id + "</span> <br>" +
          "<strong>Annotated</strong>: <span>" + d.annotated + "</span> <br>" +
          "<strong>Significant</strong>: <span>" + d.significant / d.annotated + "</span> <br>" +
          "<strong>Classic P-Val</strong>: <span>" + d.classic_pval + "</span> <br>" +
          "<strong>Elim Method P-Val</strong>: <span>" + d.elim_pval + "</span> <br>"
      });
    group.call(tip);

    const objects = group
      .append('svg')
      .classed('objects', true)
      .attr('width', width)
      .attr('height', height);

    objects
      .selectAll('.dot')
      .data(data)
      .enter()
      .append('circle')
      .classed('dot', true)
      .attr('cy', d => this.yScale(d.term) + this.yScale.bandwidth() / 2)
      .attr('cx', d => this.xScale(-Math.log(d.elim_pval)))
      .attr('r', d => this.radiusScale(d.significant / d.annotated))
      .style('fill', d => {
        return this.colors(d.annotated);
      })
      .attr('pointer-events', 'all')
      .on('mouseover', tip.show)
      .on('mouseout', tip.hide);

    // Legend
    const legendColors = [
      { name: this.maxAnnotated, color: this.colorMax },
      { name: '', color: this.colors((this.maxAnnotated - this.minAnnotated) * .75) },
      { name: '', color: this.colors((this.maxAnnotated - this.minAnnotated) * .5) },
      { name: '', color: this.colors((this.maxAnnotated - this.minAnnotated) * .25) },
      { name: this.minAnnotated, color: this.colorMin }
    ];

    const legend = group
      .selectAll('.legend')
      .data(legendColors)
      .enter()
      .append('g')
      .classed('legend', true)
      .attr('transform', function (d, i) {
        return 'translate(0,' + i * 10 + ')';
      });

    legend
      .append('rect')
      .attr('width', 50)
      .attr('height', 10)
      .attr('x', width + 20)
      .attr('y', 50)
      .attr('fill', d => d.color)

    legend
      .append('text')
      .attr('x', width + 75)
      .attr('y', 50)
      .attr('dy', 10)
      .style('fill', '#000')
      .style('font-size', "10px")
      .attr('class', 'legend-label')
      .text(d => d.name);

    const minRad = this.radiusScale(this.minRadius);
    const maxRad = this.radiusScale(this.maxRadius);
    const radDiff = maxRad - minRad;

    const legendCircleContent = [
      { name: this.minRadius, radius: minRad },
      { name: minRad + radDiff * .25, radius: minRad + radDiff * .25 },
      { name: minRad + radDiff * .5, radius: minRad + radDiff * .5 },
      { name: minRad + radDiff * .75, radius: minRad + radDiff * .75 },
      { name: this.maxRadius, radius: maxRad },
    ];

    const legendCircle = group
      .selectAll('.legendCircle')
      .data(legendCircleContent)
      .enter()
      .append('g')
      .classed('legendCircle', true)
      .attr('transform', function (d, i) {
        return 'translate(0,' + i *30 + ')';
      });

    legendCircle
      .append('circle')
      .attr('r', d => d.radius)
      .attr('cx', width + 40)
      .attr('cy', 200)
      .attr('fill', "rgba(0,0,0,.7")

    legendCircle
      .append('text')
      .attr('x', width + 75)
      .attr('y', 200)
      .attr('dy', ".32em")
      .style('fill', '#000')
      .style('font-size', "10px")
      .attr('class', 'legend-label')
      .text(d => d.name.toFixed(2));

  }
}
